fix qca-nss-clients compile error
```
ccache aarch64-openwrt-linux-musl-gcc -Wp,-MMD,/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr/.nss_clmapmgr.o.d -nostdinc -I./arch/arm64/include -I./arch/arm64/include/generated  -I./include -I./arch/arm64/include/uapi -I./arch/arm64/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -mlittle-endian -DKASAN_SHADOW_SCALE_SHIFT= -fmacro-prefix-map=./= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mgeneral-regs-only -DCONFIG_CC_HAS_K_CONSTRAINT=1 -Wno-psabi -mabi=lp64 -fno-asynchronous-unwind-tables -fno-unwind-tables -mbranch-protection=pac-ret -Wa,-march=armv8.5-a -DARM64_ASM_ARCH='"armv8.5-a"' -DKASAN_SHADOW_SCALE_SHIFT= -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-stack-clash-protection -falign-functions=4 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wframe-larger-than=2048 -Wno-main -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-dangling-pointer -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-array-bounds -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-restrict -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-overflow -Wno-stringop-truncation -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -g -fmacro-prefix-map=/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves -O3 -pipe -mstack-protector-guard=sysreg -mstack-protector-guard-reg=sp_el0 -mstack-protector-guard-offset=1144 -I/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr/../exports -I/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr/.. -DNSS_CLIENT_BUILD_ID="\"Build Id: 05/22/24, 12:51:47\"" -DNSS_CLMAPMGR_DEBUG_LEVEL=2 -Wall -Werror -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-drv -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-crypto -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-cfi -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-nss-ecm -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/qca-ssdk/fal -I/__w/ci/ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include/nat46 -I/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/exports -DNSS_L2TPV2_ENABLED -I/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/exports -Wno-enum-conversion  -DMODULE  -DKBUILD_BASENAME='"nss_clmapmgr"' -DKBUILD_MODNAME='"qca_nss_clmapmgr"' -D__KBUILD_MODNAME=kmod_qca_nss_clmapmgr -c -o /__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr/nss_clmapmgr.o /__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr/nss_clmapmgr.c
In file included from ./include/linux/string.h:294,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./include/linux/smp.h:13,
                 from ./arch/arm64/include/asm/arch_timer.h:18,
                 from ./arch/arm64/include/asm/timex.h:8,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from ../qca-nss-clients-2023.10.04~f058ae19/clmapmgr/nss_clmapmgr.c:24:
In function 'nss_clmapmgr_get_dev_stats64',
    inlined from 'nss_clmapmgr_dev_stats64' at ../qca-nss-clients-2023.10.04~f058ae19/clmapmgr/nss_clmapmgr.c:133:2:
./include/linux/fortify-string.h:57:33: error: '__builtin_memcpy' reading 200 bytes from a region of size 0 [-Werror=stringop-overread]
   57 | #define __underlying_memcpy     __builtin_memcpy
      |                                 ^
./include/linux/fortify-string.h:648:9: note: in expansion of macro '__underlying_memcpy'
  648 |         __underlying_##op(p, q, __fortify_size);                        \
      |         ^~~~~~~~~~~~~
./include/linux/fortify-string.h:693:26: note: in expansion of macro '__fortify_memcpy_chk'
  693 | #define memcpy(p, q, s)  __fortify_memcpy_chk(p, q, s,                  \
      |                          ^~~~~~~~~~~~~~~~~~~~
../qca-nss-clients-2023.10.04~f058ae19/clmapmgr/nss_clmapmgr.c:109:9: note: in expansion of macro 'memcpy'
  109 |         memcpy(stats, &priv->stats, sizeof(struct rtnl_link_stats64));
      |         ^~~~~~
In function 'nss_clmapmgr_dev_stats64':
cc1: note: source object is likely at address zero
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:243: /__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr/nss_clmapmgr.o] Error 1
make[6]: *** [scripts/Makefile.build:480: /__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19/clmapmgr] Error 2
make[5]: *** [/__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.30/Makefile:1913: /__w/ci/ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-clients-2023.10.04~f058ae19] Error 2
```